---
name: Check PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]

jobs:
  enforce-labels:
    uses: bitwarden/gh-actions/.github/workflows/_enforce-labels.yml@main
